"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("@/app/assets/styles/main.scss");
var vue_1 = require("vue");
var pinia_1 = require("pinia");
var App_vue_1 = require("./App.vue");
var providers_1 = require("./providers");
var app = (0, vue_1.createApp)(App_vue_1.default);
app.use((0, pinia_1.createPinia)());
app.use(providers_1.router);
app.mount('#app');
